name: walk_talk
description: Walk&Talk — социальные прогулки и тематические события.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.3.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  liquid_glass_renderer: ^0.2.0-dev.4
  yandex_maps_mapkit_lite: ^4.36.0
  image_picker: ^1.2.3
  path_provider: ^2.1.6
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.0
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/actions/
    - assets/icons/common/
    - assets/images/
    - assets/images/people/
    - assets/images/cards/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf
